services:
  dbConsole:
    container_name: dbConsole_dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5000:80"
    volumes:
      - db_console_data:/var/lib/pgadmin
    networks:
      - db-network
    depends_on:
      - database

  database:
    container_name: database_dev
    image: postgres:17
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  db_data:
  db_console_data:

networks:
  db-network:
    driver: bridge
